---
driver:
  name: 'terraform'
  root_module_directory: "./test/fixtures/"

provisioner:
  name: 'terraform'

platforms:
  - name: 'aws'

verifier:
  name: 'awspec'

suites:
  - name: 'default'
    verifier:
      name: 'awspec'
      patterns:
      - 'test/integration/default/instance.rb'

